from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation
from .menu_klient import Menu_klient
from .menu_lotniska import Ui_dodawani_lotniska
from .menu_samoloty import menu_samoloty
from .menu_trasy import Ui_menu_trasy
from .menu_loty import Ui_menuloty
from .menu_rezerwacja import menu_rezerwacja
from .menu_usuwanie import Ui_usuwanie
from .info_zapis import Ui_Dialog_2
from .info_odczyt import Ui_Dialog



class Ui_System_rezerwacji_biletow(object):
    def __init__(self,system):
        self.system=system
    def setupUi(self, System_rezerwacji_biletow):
        System_rezerwacji_biletow.setObjectName("System_rezerwacji_biletow")
        System_rezerwacji_biletow.resize(1200, 600)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("modules/ikony/plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        System_rezerwacji_biletow.setWindowIcon(icon)

        System_rezerwacji_biletow.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.glowny = QtWidgets.QWidget(System_rezerwacji_biletow)
        self.glowny.setMinimumSize(QtCore.QSize(800, 600))
        self.glowny.setObjectName("glowny")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.glowny)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")



        self.lewa_ramka = QtWidgets.QFrame(self.glowny)
        self.lewa_ramka.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lewa_ramka.setMinimumSize(QtCore.QSize(400,0))
        self.lewa_ramka.setStyleSheet("background-color: rgb(83, 83, 83);border-radius:5px;")
        self.lewa_ramka.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lewa_ramka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lewa_ramka.setObjectName("lewa_ramka")



        self.verticalLayout = QtWidgets.QVBoxLayout(self.lewa_ramka)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")

        self.lewo_gora_ramka = QtWidgets.QFrame(self.lewa_ramka)
        self.lewo_gora_ramka.setMaximumSize(QtCore.QSize(16777215, 64))
        self.lewo_gora_ramka.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lewo_gora_ramka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lewo_gora_ramka.setObjectName("lewo_dol_ramka")
        self.lewo_gora_ramka.setStyleSheet("background-color: rgb(83, 83, 83);")
        self.verticalLayout .addWidget(self.lewo_gora_ramka)
        self.verticalLayout_gora = QtWidgets.QVBoxLayout(self.lewo_gora_ramka)
        self.verticalLayout_gora.setContentsMargins(0,0,0,0)
        self.verticalLayout_gora.setSpacing(0)

        self.przycisk_wysun = QtWidgets.QPushButton(self.lewo_gora_ramka)
        self.przycisk_wysun.setMinimumSize(0,60)
        self.przycisk_wysun.setStyleSheet("QPushButton{\nbackground-color: rgb(53, 53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_wysun.setIcon(QtGui.QIcon("modules/ikony/menu.png"))
        self.przycisk_wysun.setIconSize(QtCore.QSize(40,40))
        self.przycisk_wysun.clicked.connect(self.animacja)
        self.verticalLayout_gora.addWidget(self.przycisk_wysun)
        #self.przycisk_wysun



        self.przycisk_klienci = QtWidgets.QPushButton(self.lewa_ramka)
        self.przycisk_klienci.setMinimumSize(QtCore.QSize(0, 90))
        self.przycisk_klienci.setIcon(QtGui.QIcon("modules/ikony/klienci.png"))
        self.przycisk_klienci.setIconSize(QtCore.QSize(40,40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSizeF(18)
        self.przycisk_klienci.setFont(font)
        self.przycisk_klienci.setStyleSheet("background-color: rgb(53,53,53);")
        self.przycisk_klienci.setObjectName("przycisk_klienci")
        self.verticalLayout.addWidget(self.przycisk_klienci)
        self.przycisk_klienci.clicked.connect(self.przycisk_klienci_click)
        self.przycisk_klienci.setStyleSheet("QPushButton{\nbackground-color: rgb(53, 53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")


        self.przycisk_samoloty = QtWidgets.QPushButton(self.lewa_ramka)
        self.przycisk_samoloty.setMinimumSize(QtCore.QSize(0, 90))
        self.przycisk_samoloty.setIcon(QtGui.QIcon("modules/ikony/samolot.ico"))
        self.przycisk_samoloty.setIconSize(QtCore.QSize(40,40))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przycisk_samoloty.setFont(font)
        self.przycisk_samoloty.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_samoloty.setObjectName("przycisk_samoloty")
        self.verticalLayout.addWidget(self.przycisk_samoloty)
        self.przycisk_samoloty.clicked.connect(self.przycisk_samoloty_click)
        self.przycisk_samoloty.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")

        #123123

        self.przysick_trasy = QtWidgets.QPushButton(self.lewa_ramka)
        self.przysick_trasy.setMinimumSize(QtCore.QSize(0, 90))
        self.przysick_trasy.setIcon(QtGui.QIcon("modules/ikony/trasa.png"))
        self.przysick_trasy.setIconSize(QtCore.QSize(40,40))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przysick_trasy.setFont(font)
        self.przysick_trasy.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przysick_trasy.setObjectName("przysick_trasy")
        self.verticalLayout.addWidget(self.przysick_trasy)
        self.przysick_trasy.clicked.connect(self.przycisk_trasy_click)
        self.przysick_trasy.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")



        self.przycisk_lotniska = QtWidgets.QPushButton(self.lewa_ramka)
        self.przycisk_lotniska.setMinimumSize(QtCore.QSize(0, 90))
        self.przycisk_lotniska.setIcon(QtGui.QIcon("modules/ikony/lotnisko.png"))
        self.przycisk_lotniska.setIconSize(QtCore.QSize(40,40))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przycisk_lotniska.setFont(font)
        self.przycisk_lotniska.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_lotniska.setObjectName("przycisk_lotniska")
        self.verticalLayout.addWidget(self.przycisk_lotniska)
        self.przycisk_lotniska.clicked.connect(self.przycisk_lotniska_click)
        self.przycisk_lotniska.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")



        self.przycisk_loty = QtWidgets.QPushButton(self.lewa_ramka)
        self.przycisk_loty.setMinimumSize(QtCore.QSize(0, 90))
        self.przycisk_loty.setIcon(QtGui.QIcon("modules/ikony/lot.png"))
        self.przycisk_loty.setIconSize(QtCore.QSize(40,40))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przycisk_loty.setFont(font)
        self.przycisk_loty.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_loty.setObjectName("przycisk_loty")
        self.verticalLayout.addWidget(self.przycisk_loty)
        self.przycisk_loty.clicked.connect(self.przycisk_loty_click)

        self.przycisk_loty.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")





        self.lewo_dol_ramka = QtWidgets.QFrame(self.lewa_ramka)
        self.lewo_dol_ramka.setMaximumSize(QtCore.QSize(16777215, 60))
        self.lewo_dol_ramka.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lewo_dol_ramka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lewo_dol_ramka.setObjectName("lewo_dol_ramka")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.lewo_dol_ramka)



        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.przycisk_zapis = QtWidgets.QPushButton(self.lewo_dol_ramka)
        self.przycisk_zapis.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przycisk_zapis.setFont(font)
        self.przycisk_zapis.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_zapis.setObjectName("przycisk_zapis")
        self.przycisk_zapis.clicked.connect(self.przycisk_zapis_click)
        self.horizontalLayout_2.addWidget(self.przycisk_zapis)

        self.przycisk_zapis.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")

        self.przysick_odczyt = QtWidgets.QPushButton(self.lewo_dol_ramka)
        self.przysick_odczyt.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSizeF(18)
        font.setFamily("Arial")
        self.przysick_odczyt.setFont(font)
        self.przysick_odczyt.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przysick_odczyt.setObjectName("przysick_odczyt")
        self.przysick_odczyt.clicked.connect(self.przycisk_odczyt_click)
        self.horizontalLayout_2.addWidget(self.przysick_odczyt)
        self.verticalLayout.addWidget(self.lewo_dol_ramka)
        self.horizontalLayout.addWidget(self.lewa_ramka)

        self.przysick_odczyt.setStyleSheet("QPushButton{\nbackground-color: rgb(53,53,53);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")


        self.prawa_ramka = QtWidgets.QFrame(self.glowny)
        self.prawa_ramka.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.prawa_ramka.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prawa_ramka.setObjectName("prawa_ramka")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.prawa_ramka)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")



        self.miejsce_na_stos = QtWidgets.QFrame(self.prawa_ramka)
        self.miejsce_na_stos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.miejsce_na_stos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.miejsce_na_stos.setObjectName("miejsce_na_stos")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.miejsce_na_stos)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stos_tabel = QtWidgets.QStackedWidget(self.miejsce_na_stos)
        self.stos_tabel.setObjectName("stos_tabel")

        # strona klienci

        self.strona_klienci = QtWidgets.QWidget()
        self.strona_klienci.setObjectName("strona_klienci")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.strona_klienci)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.klienci_gora = QtWidgets.QFrame(self.strona_klienci)
        self.klienci_gora.setMinimumSize(QtCore.QSize(0, 80))
        self.klienci_gora.setMaximumSize(QtCore.QSize(16777215, 80))
        self.klienci_gora.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.klienci_gora.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.klienci_gora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.klienci_gora.setObjectName("klienci_gora")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.klienci_gora)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.napis_klienci = QtWidgets.QLabel(self.klienci_gora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.napis_klienci.setFont(font)
        self.napis_klienci.setObjectName("napis_klienci")
        self.verticalLayout_14.addWidget(self.napis_klienci)
        self.verticalLayout_4.addWidget(self.klienci_gora)
        self.klienci_tabela = QtWidgets.QFrame(self.strona_klienci)
        self.klienci_tabela.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.klienci_tabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.klienci_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.klienci_tabela.setObjectName("klienci_tabela")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.klienci_tabela)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabela_klienci = QtWidgets.QTableWidget(self.klienci_tabela)
        self.tabela_klienci.setObjectName("tableWidget_5")

        font.setPointSize(12)
        self.tabela_klienci.setFont(font)

        self.tabela_klienci.setColumnCount(3)
        self.tabela_klienci.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_klienci.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_klienci.setHorizontalHeaderItem(0, item)
        self.tabela_klienci.setColumnWidth(0,200)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_klienci.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_klienci.setColumnWidth(1,200)
        self.tabela_klienci.setHorizontalHeaderItem(2, item)
        self.tabela_klienci.setColumnWidth(2,200)
        self.horizontalLayout_6.addWidget(self.tabela_klienci)
        self.verticalLayout_4.addWidget(self.klienci_tabela)



        self.klienci_dol = QtWidgets.QFrame(self.strona_klienci)
        self.klienci_dol.setMinimumSize(QtCore.QSize(0, 60))
        self.klienci_dol.setMaximumSize(QtCore.QSize(16777215,16777215))
        self.klienci_dol.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.klienci_dol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.klienci_dol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.klienci_dol.setObjectName("klienci_dol")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.klienci_dol)
        self.horizontalLayout_5.setContentsMargins(0, 0, 10,0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)



        self.przycisk_usun_klienci = QtWidgets.QPushButton(self.klienci_dol)
        self.przycisk_usun_klienci.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_usun_klienci.setMinimumSize(QtCore.QSize(120,40))
        self.przycisk_usun_klienci.setObjectName("przycisk_usun_klienci")
        self.horizontalLayout_5.addWidget(self.przycisk_usun_klienci)
        self.przycisk_usun_klienci.setStyleSheet("QPushButton{\nbackground-color: rgb(222, 105, 88);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_usun_klienci.clicked.connect(self.usun_klienci)



        self.przycisk_dodaj_klienci = QtWidgets.QPushButton(self.klienci_dol)
        self.przycisk_dodaj_klienci.setMinimumSize(QtCore.QSize(120,40))
        self.przycisk_dodaj_klienci.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.przycisk_dodaj_klienci.setObjectName("przycisk_dodaj_klienci")
        self.przycisk_dodaj_klienci.setStyleSheet("QPushButton{\nbackground-color: rgb(158, 182, 83);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.horizontalLayout_5.addWidget(self.przycisk_dodaj_klienci)
        self.przycisk_dodaj_klienci.clicked.connect(self.dodaj_klienci)
        self.verticalLayout_4.addWidget(self.klienci_dol)
        self.stos_tabel.addWidget(self.strona_klienci)

        #Strona samoloty

        self.strona_samoloty = QtWidgets.QWidget()
        self.strona_samoloty.setObjectName("strona_samoloty")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.strona_samoloty)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.samoloty_gora = QtWidgets.QFrame(self.strona_samoloty)
        self.samoloty_gora.setMinimumSize(QtCore.QSize(0, 80))
        self.samoloty_gora.setMaximumSize(QtCore.QSize(16777215, 80))
        self.samoloty_gora.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.samoloty_gora.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.samoloty_gora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.samoloty_gora.setObjectName("samoloty_gora")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.samoloty_gora)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.napis_samoloty = QtWidgets.QLabel(self.samoloty_gora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.napis_samoloty.setFont(font)
        self.napis_samoloty.setObjectName("napis_samoloty")
        self.verticalLayout_15.addWidget(self.napis_samoloty)
        self.verticalLayout_5.addWidget(self.samoloty_gora)
        self.samoloty_tabela = QtWidgets.QFrame(self.strona_samoloty)
        self.samoloty_tabela.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.samoloty_tabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.samoloty_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.samoloty_tabela.setObjectName("samoloty_tabela")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.samoloty_tabela)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabela_samoloty = QtWidgets.QTableWidget(self.samoloty_tabela)
        self.tabela_samoloty.setObjectName("tabela_samoloty")
        font.setPointSize(12)
        self.tabela_samoloty.setFont(font)


        self.tabela_samoloty.setColumnCount(1)
        self.tabela_samoloty.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()


        self.tabela_samoloty.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_samoloty.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_8.addWidget(self.tabela_samoloty)
        self.verticalLayout_5.addWidget(self.samoloty_tabela)
        self.tabela_samoloty.setColumnWidth(0,200)
        self.samoloty_dol = QtWidgets.QFrame(self.strona_samoloty)
        self.samoloty_dol.setMinimumSize(QtCore.QSize(0, 60))
        self.samoloty_dol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.samoloty_dol.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.samoloty_dol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.samoloty_dol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.samoloty_dol.setObjectName("samoloty_dol")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.samoloty_dol)
        self.horizontalLayout_7.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)



        self.przycisk_usun_samoloty = QtWidgets.QPushButton(self.samoloty_dol)
        self.przycisk_usun_samoloty.setStyleSheet("QPushButton{\nbackground-color: rgb(222, 105, 88);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_usun_samoloty.setObjectName("przycisk_usun_samoloty")
        self.przycisk_usun_samoloty.clicked.connect(self.usun_samoloty)
        self.przycisk_usun_samoloty.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_7.addWidget(self.przycisk_usun_samoloty)


        self.przycisk_dodaj_samoloty = QtWidgets.QPushButton(self.samoloty_dol)
        self.przycisk_dodaj_samoloty.setStyleSheet("QPushButton{\nbackground-color: rgb(158, 182, 83);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_dodaj_samoloty.setObjectName("przycisk_dodaj_samoloty")
        self.przycisk_dodaj_samoloty.clicked.connect(self.dodaj_samoloty)
        self.przycisk_dodaj_samoloty.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_7.addWidget(self.przycisk_dodaj_samoloty)
        self.verticalLayout_5.addWidget(self.samoloty_dol)
        self.stos_tabel.addWidget(self.strona_samoloty)



        self.strona_trasy = QtWidgets.QWidget()
        self.strona_trasy.setObjectName("strona_trasy")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.strona_trasy)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.trasy_gora = QtWidgets.QFrame(self.strona_trasy)
        self.trasy_gora.setMinimumSize(QtCore.QSize(0, 80))
        self.trasy_gora.setMaximumSize(QtCore.QSize(16777215, 80))
        self.trasy_gora.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.trasy_gora.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.trasy_gora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.trasy_gora.setObjectName("trasy_gora")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.trasy_gora)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.napis_trasy = QtWidgets.QLabel(self.trasy_gora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.napis_trasy.setFont(font)
        self.napis_trasy.setObjectName("napis_trasy")
        self.verticalLayout_12.addWidget(self.napis_trasy)
        self.verticalLayout_13.addWidget(self.trasy_gora)
        self.trasy_tabela = QtWidgets.QFrame(self.strona_trasy)
        self.trasy_tabela.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.trasy_tabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.trasy_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trasy_tabela.setObjectName("trasy_tabela")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.trasy_tabela)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabela_trasy = QtWidgets.QTableWidget(self.trasy_tabela)
        self.tabela_trasy.setObjectName("tabela_trasy")

        font.setPointSize(12)
        self.tabela_trasy.setFont(font)


        self.tabela_trasy.setColumnCount(4)
        self.tabela_trasy.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()

        self.tabela_trasy.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_trasy.setColumnWidth(0,200)
        self.tabela_trasy.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_trasy.setColumnWidth(1,200)
        self.tabela_trasy.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_trasy.setColumnWidth(2,200)
        self.tabela_trasy.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_trasy.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_4.addWidget(self.tabela_trasy)
        self.verticalLayout_13.addWidget(self.trasy_tabela)
        self.trasy_dol = QtWidgets.QFrame(self.strona_trasy)
        self.trasy_dol.setMinimumSize(QtCore.QSize(0, 60))
        self.trasy_dol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.trasy_dol.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.trasy_dol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trasy_dol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trasy_dol.setObjectName("trasy_dol")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.trasy_dol)
        self.horizontalLayout_3.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.przycisk_usun = QtWidgets.QPushButton(self.trasy_dol)
        self.przycisk_usun.setStyleSheet("QPushButton{\nbackground-color: rgb(222, 105, 88);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_usun.setObjectName("przycisk_usun")
        self.przycisk_usun.clicked.connect(self.usun_trasy)
        self.przycisk_usun.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_3.addWidget(self.przycisk_usun)
        self.przycisk_dodaj = QtWidgets.QPushButton(self.trasy_dol)
        self.przycisk_dodaj.setStyleSheet("QPushButton{\nbackground-color: rgb(158, 182, 83);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_dodaj.setObjectName("przycisk_dodaj")
        self.przycisk_dodaj.clicked.connect(self.dodaj_trasy)
        self.przycisk_dodaj.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_3.addWidget(self.przycisk_dodaj)
        self.verticalLayout_13.addWidget(self.trasy_dol)
        self.stos_tabel.addWidget(self.strona_trasy)



        self.strona_lotniska = QtWidgets.QWidget()
        self.strona_lotniska.setObjectName("strona_lotniska")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.strona_lotniska)
        self.verticalLayout_6.setContentsMargins(0, 0,0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lotniska_gora = QtWidgets.QFrame(self.strona_lotniska)
        self.lotniska_gora.setMinimumSize(QtCore.QSize(0, 80))
        self.lotniska_gora.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lotniska_gora.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.lotniska_gora.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lotniska_gora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lotniska_gora.setObjectName("lotniska_gora")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.lotniska_gora)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.napis_lotniska = QtWidgets.QLabel(self.lotniska_gora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.napis_lotniska.setFont(font)
        self.napis_lotniska.setObjectName("napis_lotniska")
        self.verticalLayout_16.addWidget(self.napis_lotniska)
        self.verticalLayout_6.addWidget(self.lotniska_gora)
        self.lotniska_tabela = QtWidgets.QFrame(self.strona_lotniska)
        self.lotniska_tabela.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.lotniska_tabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lotniska_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lotniska_tabela.setObjectName("lotniska_tabela")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.lotniska_tabela)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabela_lotniska = QtWidgets.QTableWidget(self.lotniska_tabela)
        self.tabela_lotniska.setObjectName("tabela_lotniska")

        font.setPointSize(12)
        self.tabela_lotniska.setFont(font)


        self.tabela_lotniska.setColumnCount(2)
        self.tabela_lotniska.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_lotniska.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_lotniska.setColumnWidth(0,200)
        self.tabela_lotniska.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(15)
        item.setFont(font)
        self.tabela_lotniska.setColumnWidth(1,200)
        self.tabela_lotniska.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_9.addWidget(self.tabela_lotniska)
        self.verticalLayout_6.addWidget(self.lotniska_tabela)
        self.lotniska_dol = QtWidgets.QFrame(self.strona_lotniska)
        self.lotniska_dol.setMinimumSize(QtCore.QSize(0, 60))
        self.lotniska_dol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lotniska_dol.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.lotniska_dol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lotniska_dol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lotniska_dol.setObjectName("lotniska_dol")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.lotniska_dol)
        self.horizontalLayout_10.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.przycisk_usun_lotniska = QtWidgets.QPushButton(self.lotniska_dol)
        self.przycisk_usun_lotniska.setStyleSheet("QPushButton{\nbackground-color: rgb(222, 105, 88);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_usun_lotniska.setObjectName("przycisk_usun_lotniska")
        self.przycisk_usun_lotniska.clicked.connect(self.usun_lotniska)
        self.przycisk_usun_lotniska.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_10.addWidget(self.przycisk_usun_lotniska)

        self.przycisk_dodaj_lotniska = QtWidgets.QPushButton(self.lotniska_dol)
        self.przycisk_dodaj_lotniska.setStyleSheet("QPushButton{\nbackground-color: rgb(158, 182, 83);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_dodaj_lotniska.setObjectName("przycisk_dodaj_lotniska")
        self.przycisk_dodaj_lotniska.clicked.connect(self.dodaj_lotniska)
        self.przycisk_dodaj_lotniska.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_10.addWidget(self.przycisk_dodaj_lotniska)
        self.verticalLayout_6.addWidget(self.lotniska_dol)
        self.stos_tabel.addWidget(self.strona_lotniska)



        self.strona_loty = QtWidgets.QWidget()
        self.strona_loty.setObjectName("stron_loty")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.strona_loty)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.loty_gora = QtWidgets.QFrame(self.strona_loty)
        self.loty_gora.setMinimumSize(QtCore.QSize(0, 80))
        self.loty_gora.setMaximumSize(QtCore.QSize(16777215, 80))
        self.loty_gora.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.loty_gora.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loty_gora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.loty_gora.setObjectName("loty_gora")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.loty_gora)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.napis_loty = QtWidgets.QLabel(self.loty_gora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.napis_loty.setFont(font)
        self.napis_loty.setObjectName("napis_loty")
        self.verticalLayout_17.addWidget(self.napis_loty)
        self.verticalLayout_7.addWidget(self.loty_gora)
        self.loty_tabela = QtWidgets.QFrame(self.strona_loty)
        self.loty_tabela.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.loty_tabela.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loty_tabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loty_tabela.setObjectName("loty_tabela")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.loty_tabela)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tabela_loty = QtWidgets.QTableWidget(self.loty_tabela)
        self.tabela_loty.setObjectName("tabela_loty")

        font.setPointSize(12)
        self.tabela_loty.setFont(font)


        self.tabela_loty.setColumnCount(7)
        self.tabela_loty.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tabela_loty.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(0,135)
        self.tabela_loty.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(1,135)
        self.tabela_loty.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(2,80)
        self.tabela_loty.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(3,60)
        self.tabela_loty.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(4,130)
        self.tabela_loty.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(5,100)
        self.tabela_loty.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font.setPointSize(12)
        item.setFont(font)
        self.tabela_loty.setColumnWidth(6,121)
        self.tabela_loty.setHorizontalHeaderItem(6, item)

        item = QtWidgets.QTableWidgetItem()
        self.tabela_loty.setItem(0, 0, item)

        self.horizontalLayout_12.addWidget(self.tabela_loty)
        self.verticalLayout_7.addWidget(self.loty_tabela)
        self.loty_dol = QtWidgets.QFrame(self.strona_loty)
        self.loty_dol.setMinimumSize(QtCore.QSize(0, 60))
        self.loty_dol.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loty_dol.setStyleSheet("background-color: rgb(53, 53, 53);border-radius:5px;")
        self.loty_dol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loty_dol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loty_dol.setObjectName("loty_dol")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.loty_dol)
        self.horizontalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.przycisk_usun_loty = QtWidgets.QPushButton(self.loty_dol)
        self.przycisk_usun_loty.setStyleSheet("QPushButton{\nbackground-color: rgb(222, 105, 88);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_usun_loty.setObjectName("przycisk_usun_loty")
        self.przycisk_usun_loty.clicked.connect(self.usun_loty)
        self.przycisk_usun_loty.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_11.addWidget(self.przycisk_usun_loty)

        self.przycisk_dodaj_loty = QtWidgets.QPushButton(self.loty_dol)
        self.przycisk_dodaj_loty.setStyleSheet("QPushButton{\nbackground-color: rgb(158, 182, 83);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_dodaj_loty.setObjectName("przycisk_dodaj_loty")
        self.przycisk_dodaj_loty.clicked.connect(self.dodaj_loty)
        self.przycisk_dodaj_loty.setMinimumSize(QtCore.QSize(120,40))

        self.przycisk_rezerwacje = QtWidgets.QPushButton(self.loty_dol)
        self.przycisk_rezerwacje.setStyleSheet("QPushButton{\nbackground-color: rgb(98, 174, 163);border:none;color:rgb(255,255,255);\n}\nQPushButton:hover{\ncolor:rgb(0,0,0);background-color: rgb(255, 170, 0);\n}")
        self.przycisk_rezerwacje.setObjectName("przycisk_rezerwacje")
        self.przycisk_rezerwacje.clicked.connect(self.rezerwacja_click)
        self.przycisk_rezerwacje.setMinimumSize(QtCore.QSize(120,40))
        self.horizontalLayout_11.addWidget(self.przycisk_rezerwacje)


        self.horizontalLayout_11.addWidget(self.przycisk_dodaj_loty)
        self.verticalLayout_7.addWidget(self.loty_dol)
        self.stos_tabel.addWidget(self.strona_loty)
        self.verticalLayout_3.addWidget(self.stos_tabel)
        self.verticalLayout_2.addWidget(self.miejsce_na_stos)
        self.horizontalLayout.addWidget(self.prawa_ramka)
        System_rezerwacji_biletow.setCentralWidget(self.glowny)

        self.retranslateUi(System_rezerwacji_biletow)
        self.stos_tabel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(System_rezerwacji_biletow)

        self.stos_tabel.setCurrentWidget(self.strona_klienci)
        self.tabela_klienci.setRowCount(len(self.system.get_klienci()))
        for i in range(len(self.system.get_klienci())):
            self.tabela_klienci.setItem(i, 0, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_imie()))
            self.tabela_klienci.setItem(i, 1, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_nazwisko()))
            self.tabela_klienci.setItem(i, 2, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_pesel()))

    def retranslateUi(self, System_rezerwacji_biletow):
        _translate = QtCore.QCoreApplication.translate
        System_rezerwacji_biletow.setWindowTitle(_translate("System_rezerwacji_biletow", "System rezerwacji biletow"))
        self.przycisk_klienci.setText(_translate("System_rezerwacji_biletow", "Klienci"))
        self.przycisk_samoloty.setText(_translate("System_rezerwacji_biletow", "Samoloty"))
        self.przysick_trasy.setText(_translate("System_rezerwacji_biletow", "Trasy"))
        self.przycisk_lotniska.setText(_translate("System_rezerwacji_biletow", "Lotniska"))
        self.przycisk_loty.setText(_translate("System_rezerwacji_biletow", "Loty"))
        self.przycisk_rezerwacje.setText(_translate("System_rezerwacji_biletow", "Rezerwacja"))
        self.przycisk_zapis.setText(_translate("System_rezerwacji_biletow", "Zapis"))
        self.przysick_odczyt.setText(_translate("System_rezerwacji_biletow", "Odczyt"))
        self.napis_klienci.setText(_translate("System_rezerwacji_biletow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffaa00;\">Klienci</span></p></body></html>"))
        item = self.tabela_klienci.verticalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "1"))
        item = self.tabela_klienci.horizontalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "Imie/Nazwa"))
        item = self.tabela_klienci.horizontalHeaderItem(1)
        item.setText(_translate("System_rezerwacji_biletow", "Nazwisko"))
        item = self.tabela_klienci.horizontalHeaderItem(2)
        item.setText(_translate("System_rezerwacji_biletow", "Pesel/Nip"))
        self.przycisk_usun_klienci.setText(_translate("System_rezerwacji_biletow", "Usuń"))
        self.przycisk_dodaj_klienci.setText(_translate("System_rezerwacji_biletow", "Dodaj"))
        self.napis_samoloty.setText(_translate("System_rezerwacji_biletow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffaa00;\">Samoloty</span></p></body></html>"))
        item = self.tabela_samoloty.verticalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "1"))
        item = self.tabela_samoloty.horizontalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "Rodzaj samolotu"))
        self.przycisk_usun_samoloty.setText(_translate("System_rezerwacji_biletow", "Usuń"))
        self.przycisk_dodaj_samoloty.setText(_translate("System_rezerwacji_biletow", "Dodaj"))
        self.napis_trasy.setText(_translate("System_rezerwacji_biletow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffaa00;\">Trasy</span></p></body></html>"))
        item = self.tabela_trasy.verticalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "1"))
        item = self.tabela_trasy.horizontalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "Punkt startowy"))
        item = self.tabela_trasy.horizontalHeaderItem(1)
        item.setText(_translate("System_rezerwacji_biletow", "Punkt docelowy"))
        item = self.tabela_trasy.horizontalHeaderItem(2)
        item.setText(_translate("System_rezerwacji_biletow", "Odległość"))
        item = self.tabela_trasy.horizontalHeaderItem(3)
        item.setText(_translate("System_rezerwacji_biletow", "Czas"))
        self.przycisk_usun.setText(_translate("System_rezerwacji_biletow", "Usuń"))
        self.przycisk_dodaj.setText(_translate("System_rezerwacji_biletow", "Dodaj"))
        self.napis_lotniska.setText(_translate("System_rezerwacji_biletow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffaa00;\">Lotniska</span></p></body></html>"))
        item = self.tabela_lotniska.verticalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "1"))
        item = self.tabela_lotniska.horizontalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "Miasto"))
        item = self.tabela_lotniska.horizontalHeaderItem(1)
        item.setText(_translate("System_rezerwacji_biletow", "Państwo"))
        self.przycisk_usun_lotniska.setText(_translate("System_rezerwacji_biletow", "Usuń"))
        self.przycisk_dodaj_lotniska.setText(_translate("System_rezerwacji_biletow", "Dodaj"))
        self.napis_loty.setText(_translate("System_rezerwacji_biletow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#ffaa00;\">Loty</span></p></body></html>"))
        item = self.tabela_loty.verticalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "1"))
        item = self.tabela_loty.horizontalHeaderItem(0)
        item.setText(_translate("System_rezerwacji_biletow", "Punkt Startowy"))
        item = self.tabela_loty.horizontalHeaderItem(1)
        item.setText(_translate("System_rezerwacji_biletow", "Punkt Docelowy"))
        item = self.tabela_loty.horizontalHeaderItem(2)
        item.setText(_translate("System_rezerwacji_biletow", "Długość"))
        item = self.tabela_loty.horizontalHeaderItem(3)
        item.setText(_translate("System_rezerwacji_biletow", "Czas"))
        item = self.tabela_loty.horizontalHeaderItem(4)
        item.setText(_translate("System_rezerwacji_biletow", "Rodzaj Samolotu"))
        item = self.tabela_loty.horizontalHeaderItem(5)
        item.setText(_translate("System_rezerwacji_biletow", "Data"))
        item = self.tabela_loty.horizontalHeaderItem(6)
        item.setText(_translate("System_rezerwacji_biletow", "miejsca zaj/max"))

        self.przycisk_usun_loty.setText(_translate("System_rezerwacji_biletow", "Usuń"))
        self.przycisk_dodaj_loty.setText(_translate("System_rezerwacji_biletow", "Dodaj"))

    def przycisk_klienci_click(self):
        self.stos_tabel.setCurrentWidget(self.strona_klienci)
        self.tabela_klienci.setRowCount(len(self.system.get_klienci()))
        for i in range(len(self.system.get_klienci())):
            self.tabela_klienci.setItem(i, 0, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_imie()))
            self.tabela_klienci.setItem(i, 1, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_nazwisko()))
            self.tabela_klienci.setItem(i, 2, QtWidgets.QTableWidgetItem(self.system.get_klienci()[i].get_pesel()))

    def przycisk_samoloty_click(self):
        self.stos_tabel.setCurrentWidget(self.strona_samoloty)
        self.tabela_samoloty.setRowCount(len(self.system.get_samoloty()))
        for i in range(len(self.system.get_samoloty())):
            self.tabela_samoloty.setItem(i,0,QtWidgets.QTableWidgetItem(self.system.get_samoloty()[i].__str__()))

    def przycisk_trasy_click(self):
        self.stos_tabel.setCurrentWidget(self.strona_trasy)
        self.tabela_trasy.setRowCount(len(self.system.get_trasy()))
        for i in range(len(self.system.get_trasy())):
            self.tabela_trasy.setItem(i,0,QtWidgets.QTableWidgetItem(str(self.system.get_trasy()[i].get_lotniska_w_trasy()[0])))
            self.tabela_trasy.setItem(i,1,QtWidgets.QTableWidgetItem(str(self.system.get_trasy()[i].get_lotniska_w_trasy()[1])))
            self.tabela_trasy.setItem(i,2,QtWidgets.QTableWidgetItem(str(self.system.get_trasy()[i].get_czas())+" km"))
            self.tabela_trasy.setItem(i,3,QtWidgets.QTableWidgetItem(str(self.system.get_trasy()[i].get_odleglosc())+" min"))


    def przycisk_lotniska_click(self):
        self.stos_tabel.setCurrentWidget(self.strona_lotniska)
        self.tabela_lotniska.setRowCount(len(self.system.get_lotniska()))
        for i in range(len(self.system.get_lotniska())):
            self.tabela_lotniska.setItem(i,0,QtWidgets.QTableWidgetItem(self.system.get_lotniska()[i].get_miasto()))
            self.tabela_lotniska.setItem(i,1,QtWidgets.QTableWidgetItem(self.system.get_lotniska()[i].get_panstwo()))

    def przycisk_loty_click(self):
        self.stos_tabel.setCurrentWidget(self.strona_loty)
        self.tabela_loty.setRowCount(len(self.system.get_loty()))

        for i in range(len(self.system.get_loty())):
            self.tabela_loty.setItem(i,0,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_trasa().get_lotniska_w_trasy()[0])))
            self.tabela_loty.setItem(i,1,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_trasa().get_lotniska_w_trasy()[1])))
            self.tabela_loty.setItem(i,2,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_trasa().get_czas())))
            self.tabela_loty.setItem(i,3,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_trasa().get_odleglosc())))
            self.tabela_loty.setItem(i,4,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_samolot())))
            self.tabela_loty.setItem(i,5,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_data())))
            self.tabela_loty.setItem(i,6,QtWidgets.QTableWidgetItem(str(self.system.get_loty()[i].get_zajete())+"/"+str(self.system.get_loty()[i].get_samolot().get_miejsca())))


    def rezerwacja_click(self):
        Dialog = QtWidgets.QDialog()
        ui = menu_rezerwacja(self.system)
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
        self.przycisk_loty_click()

    def przycisk_zapis_click(self):

        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog_2()
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
        self.system.zapisz_wszystko()

    def przycisk_odczyt_click(self):
        Dialog = QtWidgets.QDialog()
        ui = Ui_Dialog(self.system)
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()

    def dodaj_klienci(self):
        Dialog = QtWidgets.QDialog()
        ui = Menu_klient(self.system)
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
        self.przycisk_klienci_click()

    def usun_klienci(self):
        usuwanie = QtWidgets.QDialog()
        ui = Ui_usuwanie(self.system,1)
        ui.setupUi(usuwanie)
        usuwanie.show()
        usuwanie.exec_()
        self.przycisk_klienci_click()

    def dodaj_samoloty(self):
        Dialog = QtWidgets.QDialog()
        ui = menu_samoloty(self.system)
        ui.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
        self.przycisk_samoloty_click()

    def usun_samoloty(self):
        usuwanie = QtWidgets.QDialog()
        ui = Ui_usuwanie(self.system,2)
        ui.setupUi(usuwanie)
        usuwanie.show()
        usuwanie.exec_()
        self.przycisk_samoloty_click()

    def dodaj_trasy(self):
        menu_trasy = QtWidgets.QDialog()
        ui = Ui_menu_trasy(self.system)
        ui.setupUi(menu_trasy)
        menu_trasy.show()
        menu_trasy.exec_()
        self.przycisk_trasy_click()

    def usun_trasy(self):
        usuwanie = QtWidgets.QDialog()
        ui = Ui_usuwanie(self.system,3)
        ui.setupUi(usuwanie)
        usuwanie.show()
        usuwanie.exec_()
        self.przycisk_trasy_click()

    def dodaj_lotniska(self):
        dodawani_lotniska = QtWidgets.QDialog()
        ui = Ui_dodawani_lotniska(self.system)
        ui.setupUi(dodawani_lotniska)
        dodawani_lotniska.show()
        dodawani_lotniska.exec_()
        self.przycisk_lotniska_click()

    def usun_lotniska(self):
        usuwanie = QtWidgets.QDialog()
        ui = Ui_usuwanie(self.system,4)
        ui.setupUi(usuwanie)
        usuwanie.show()
        usuwanie.exec_()
        self.przycisk_lotniska_click()

    def dodaj_loty(self):
        menuloty = QtWidgets.QDialog()
        ui = Ui_menuloty(self.system)
        ui.setupUi(menuloty)
        menuloty.show()
        menuloty.exec_()
        self.przycisk_loty_click()

    def usun_loty(self):
        usuwanie = QtWidgets.QDialog()
        ui = Ui_usuwanie(self.system,5)
        ui.setupUi(usuwanie)
        usuwanie.show()
        usuwanie.exec_()
        self.przycisk_loty_click()

    def animacja(self):
        self.anim = QPropertyAnimation(self.lewa_ramka,b"minimumWidth")
        self.anim.setDuration(400)
        if self.lewa_ramka.width() == 400:
            self.anim.setStartValue(400)
            self.anim.setEndValue(120)
            self.przycisk_klienci.setText("")
            self.przycisk_samoloty.setText("")
            self.przysick_trasy.setText("")
            self.przycisk_lotniska.setText("")
            self.przycisk_loty.setText("")
            self.przysick_odczyt.hide()
        else:
            self.anim.setStartValue(120)
            self.anim.setEndValue(400)
            self.przycisk_klienci.setText("Klienci")
            self.przycisk_samoloty.setText("Samoloty")
            self.przysick_trasy.setText("Trasy")
            self.przycisk_lotniska.setText("Lotniska")
            self.przycisk_loty.setText("Loty")
            self.przysick_odczyt.show()
        self.anim.start()
